export interface Database {
  public: {
    Tables: {
      cars: {
        Row: {
          id: string;
          make: string;
          model: string;
          year: number;
          mileage: number | null;
          price: number;
          condition: string;
          color: string | null;
          transmission: string | null;
          fuel_type: string | null;
          description: string | null;
          location: string | null;
          images: string[];
          status: 'available' | 'sold';
          is_hidden: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          make: string;
          model: string;
          year: number;
          mileage?: number | null;
          price: number;
          condition: string;
          color?: string | null;
          transmission?: string | null;
          fuel_type?: string | null;
          description?: string | null;
          location?: string | null;
          images?: string[];
          status?: 'available' | 'sold';
          is_hidden?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          make?: string;
          model?: string;
          year?: number;
          mileage?: number | null;
          price?: number;
          condition?: string;
          color?: string | null;
          transmission?: string | null;
          fuel_type?: string | null;
          description?: string | null;
          location?: string | null;
          images?: string[];
          status?: string;
          is_hidden?: boolean;
          created_at?: string;
        };
      };
      sales_agreements: {
        Row: {
          id: string;
          agreement_number: string;
          car_id: string | null;
          car_make: string;
          car_model: string;
          car_year: number;
          car_mileage: number | null;
          car_color: string | null;
          car_transmission: string | null;
          car_fuel_type: string | null;
          car_condition: string | null;
          car_image: string | null;
          seller_name: string;
          seller_id_type: string;
          seller_id_number: string;
          seller_kra_pin: string | null;
          seller_phone: string;
          seller_email: string | null;
          seller_address: string;
          buyer_name: string;
          buyer_id_type: string;
          buyer_id_number: string;
          buyer_kra_pin: string | null;
          buyer_phone: string;
          buyer_email: string | null;
          buyer_address: string;
          sale_price: number;
          deposit_amount: number;
          balance_amount: number;
          payment_method: string;
          sale_date: string;
          transfer_date: string | null;
          additional_terms: string | null;
          witness_name: string | null;
          witness_id: string | null;
          witness_phone: string | null;
          status: 'active' | 'completed' | 'cancelled';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          agreement_number: string;
          car_id?: string | null;
          car_make: string;
          car_model: string;
          car_year: number;
          car_mileage?: number | null;
          car_color?: string | null;
          car_transmission?: string | null;
          car_fuel_type?: string | null;
          car_condition?: string | null;
          car_image?: string | null;
          seller_name: string;
          seller_id_type: string;
          seller_id_number: string;
          seller_kra_pin?: string | null;
          seller_phone: string;
          seller_email?: string | null;
          seller_address: string;
          buyer_name: string;
          buyer_id_type: string;
          buyer_id_number: string;
          buyer_kra_pin?: string | null;
          buyer_phone: string;
          buyer_email?: string | null;
          buyer_address: string;
          sale_price: number;
          deposit_amount?: number;
          balance_amount: number;
          payment_method: string;
          sale_date: string;
          transfer_date?: string | null;
          additional_terms?: string | null;
          witness_name?: string | null;
          witness_id?: string | null;
          witness_phone?: string | null;
          status?: 'active' | 'completed' | 'cancelled';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          agreement_number?: string;
          car_id?: string | null;
          car_make?: string;
          car_model?: string;
          car_year?: number;
          car_mileage?: number | null;
          car_color?: string | null;
          car_transmission?: string | null;
          car_fuel_type?: string | null;
          car_condition?: string | null;
          car_image?: string | null;
          seller_name?: string;
          seller_id_type?: string;
          seller_id_number?: string;
          seller_kra_pin?: string | null;
          seller_phone?: string;
          seller_email?: string | null;
          seller_address?: string;
          buyer_name?: string;
          buyer_id_type?: string;
          buyer_id_number?: string;
          buyer_kra_pin?: string | null;
          buyer_phone?: string;
          buyer_email?: string | null;
          buyer_address?: string;
          sale_price?: number;
          deposit_amount?: number;
          balance_amount?: number;
          payment_method?: string;
          sale_date?: string;
          transfer_date?: string | null;
          additional_terms?: string | null;
          witness_name?: string | null;
          witness_id?: string | null;
          witness_phone?: string | null;
          status?: 'active' | 'completed' | 'cancelled';
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}

export type Car = Database['public']['Tables']['cars']['Row'];
export type CarInsert = Database['public']['Tables']['cars']['Insert'];
export type CarUpdate = Database['public']['Tables']['cars']['Update'];

export type SalesAgreement = Database['public']['Tables']['sales_agreements']['Row'];
export type SalesAgreementInsert = Database['public']['Tables']['sales_agreements']['Insert'];
export type SalesAgreementUpdate = Database['public']['Tables']['sales_agreements']['Update'];